### ISSUE TITLE
FATAL EXCEPTION: AsyncTask

### ISSUE THREAD

**Issue by veled** [dbotha/Android-Photo-Picker#1]
I'm using InstagramPhotoPicker already and I love it, great work.

But in this library, always get "FATAL EXCEPTION: AsyncTask #2" error. Try to figure it but I can't.

[errrrr.txt](https://github.com/dbotha/Android-Photo-Picker/files/32525/errrrr.txt)

**Comment by dbotha** [comment]
Hi @veled - do you have the READ_EXTERNAL_STORAGE permission in your manifest?

**Comment by veled** [comment]
I tryed  "READ_EXTERNAL_STORAGE" and "READ_EXTERNAL_STORAGE" android:maxSdkVersion="18"" but didn't work. I can access stroge with ACTION_PICK.

**Comment by dbotha** [comment]
@veled - does the sample app work for you if you clone the repo and run it on the same device?

**Comment by veled** [comment]
Sample app worked after installing buildToolsVersion "21.1.2". But in my project I'm using  buildToolsVersion "23.0.1". Still instagram picker working and Android picker not working.

**Comment by veled** [comment]
I installed Adnroid Studio on an other computer. Created a new aplication. Installed library on maverick and do your steps on readme.md. Added read external strorage permision on android.manifest. Every thing is as it is supposed to be. But still the same error. Sample app running with no problem but the library isn't working.

**Comment by veled** [comment]
by the way, sample app using the library as a module. and when I try to add the module in my projeckt its always giving the "Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer" error.
